//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customer.TestSLATE.Mnemonic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Customer.TestSLATE.Mnemonic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool Acquire {
            get {
                object obj = ResourceManager.GetObject("Acquire", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Mnemonic.
        /// </summary>
        internal static string AddSourcePermission {
            get {
                return ResourceManager.GetString("AddSourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Mnemonic.
        /// </summary>
        internal static string AddTemplate {
            get {
                return ResourceManager.GetString("AddTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool Calibrate {
            get {
                object obj = ResourceManager.GetObject("Calibrate", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.1.
        /// </summary>
        internal static string CircularBufferInSeconds {
            get {
                return ResourceManager.GetString("CircularBufferInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.*.
        /// </summary>
        internal static string CompatibleWithVersions {
            get {
                return ResourceManager.GetString("CompatibleWithVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemExplorer/Configuration.
        /// </summary>
        internal static string ConfigLevelPluginPath {
            get {
                return ResourceManager.GetString("ConfigLevelPluginPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cfg.
        /// </summary>
        internal static string ConfigPluginAppender {
            get {
                return ResourceManager.GetString("ConfigPluginAppender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete rows?.
        /// </summary>
        internal static string ConfirmationDeleteRows {
            get {
                return ResourceManager.GetString("ConfirmationDeleteRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string DataSourceRate {
            get {
                return ResourceManager.GetString("DataSourceRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog Input Channel.
        /// </summary>
        internal static string DefaultAIDescription {
            get {
                return ResourceManager.GetString("DefaultAIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewAI.
        /// </summary>
        internal static string DefaultAIName {
            get {
                return ResourceManager.GetString("DefaultAIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog Output Channel.
        /// </summary>
        internal static string DefaultAODescription {
            get {
                return ResourceManager.GetString("DefaultAODescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewAO.
        /// </summary>
        internal static string DefaultAOName {
            get {
                return ResourceManager.GetString("DefaultAOName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Balance.
        /// </summary>
        internal static string DefaultBalName {
            get {
                return ResourceManager.GetString("DefaultBalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Description.
        /// </summary>
        internal static string DefaultDescription {
            get {
                return ResourceManager.GetString("DefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Input Channel.
        /// </summary>
        internal static string DefaultDIDescription {
            get {
                return ResourceManager.GetString("DefaultDIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewDI.
        /// </summary>
        internal static string DefaultDIName {
            get {
                return ResourceManager.GetString("DefaultDIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Output Channel.
        /// </summary>
        internal static string DefaultDODescription {
            get {
                return ResourceManager.GetString("DefaultDODescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewDO.
        /// </summary>
        internal static string DefaultDOName {
            get {
                return ResourceManager.GetString("DefaultDOName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\temp\temp.txt.
        /// </summary>
        internal static string DefaultFilePath {
            get {
                return ResourceManager.GetString("DefaultFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool Diagnostics {
            get {
                object obj = ResourceManager.GetObject("Diagnostics", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Mnemonic.
        /// </summary>
        internal static string EditNode {
            get {
                return ResourceManager.GetString("EditNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Mnemonic.
        /// </summary>
        internal static string EditTemplate {
            get {
                return ResourceManager.GetString("EditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnemonic caught fire..
        /// </summary>
        internal static string ErrorMessage0001 {
            get {
                return ResourceManager.GetString("ErrorMessage0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        internal static int EUDType {
            get {
                object obj = ResourceManager.GetObject("EUDType", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOURCE.
        /// </summary>
        internal static string ExecCode {
            get {
                return ResourceManager.GetString("ExecCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOC.
        /// </summary>
        internal static string ExecName {
            get {
                return ResourceManager.GetString("ExecName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Mnemonic Calibration.
        /// </summary>
        internal static string ExecuteTemplateCalibration {
            get {
                return ResourceManager.GetString("ExecuteTemplateCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        internal static string ExecuteTemplateDiagnostic {
            get {
                return ResourceManager.GetString("ExecuteTemplateDiagnostic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string ExecuteTemplateExecute {
            get {
                return ResourceManager.GetString("ExecuteTemplateExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 100000000.
        /// </summary>
        internal static int HighRFMEnd {
            get {
                object obj = ResourceManager.GetObject("HighRFMEnd", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 90000000.
        /// </summary>
        internal static int HighRFMStart {
            get {
                object obj = ResourceManager.GetObject("HighRFMStart", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool Initialize {
            get {
                object obj = ResourceManager.GetObject("Initialize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemExplorer/Mnemonic.
        /// </summary>
        internal static string InitializeAtPath {
            get {
                return ResourceManager.GetString("InitializeAtPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool ListenForAll {
            get {
                object obj = ResourceManager.GetObject("ListenForAll", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainWindow.
        /// </summary>
        internal static string MainMenuPluginPath {
            get {
                return ResourceManager.GetString("MainMenuPluginPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Manufacturer.
        /// </summary>
        internal static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate Mnemonic Source.
        /// </summary>
        internal static string MenuItemCalibrateSource {
            get {
                return ResourceManager.GetString("MenuItemCalibrateSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnemonic.
        /// </summary>
        internal static string MenuItemTemplate {
            get {
                return ResourceManager.GetString("MenuItemTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnu.
        /// </summary>
        internal static string MenuPluginAppender {
            get {
                return ResourceManager.GetString("MenuPluginAppender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnemonic.
        /// </summary>
        internal static string Mnemonic {
            get {
                return ResourceManager.GetString("Mnemonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Name cannot be blank.
        /// </summary>
        internal static string NoBlankSourceName {
            get {
                return ResourceManager.GetString("NoBlankSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnemonic.
        /// </summary>
        internal static string NodeName {
            get {
                return ResourceManager.GetString("NodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOC.
        /// </summary>
        internal static string PCName {
            get {
                return ResourceManager.GetString("PCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Customer.TestSLATE.Mnemonic.llb\Performance Functions.vi.
        /// </summary>
        internal static string PerformanceFunctionsPath {
            get {
                return ResourceManager.GetString("PerformanceFunctionsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnemonic.
        /// </summary>
        internal static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.0.
        /// </summary>
        internal static string PluginVersion {
            get {
                return ResourceManager.GetString("PluginVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 28880.
        /// </summary>
        internal static int PortNumber {
            get {
                object obj = ResourceManager.GetObject("PortNumber", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnemonic.
        /// </summary>
        internal static string ProcessName {
            get {
                return ResourceManager.GetString("ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool ReloadDB {
            get {
                object obj = ResourceManager.GetObject("ReloadDB", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Mnemonic.
        /// </summary>
        internal static string RemoveNode {
            get {
                return ResourceManager.GetString("RemoveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Mnemonic.
        /// </summary>
        internal static string RemoveTemplate {
            get {
                return ResourceManager.GetString("RemoveTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string RenameTemplate {
            get {
                return ResourceManager.GetString("RenameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool Required {
            get {
                object obj = ResourceManager.GetObject("Required", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool RequiredSource {
            get {
                object obj = ResourceManager.GetObject("RequiredSource", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string RFMExtraMemoryInBytes {
            get {
                return ResourceManager.GetString("RFMExtraMemoryInBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to -1.
        /// </summary>
        internal static int SourceID {
            get {
                object obj = ResourceManager.GetObject("SourceID", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemExplorer/Sources.
        /// </summary>
        internal static string SourceLevelPluginPath {
            get {
                return ResourceManager.GetString("SourceLevelPluginPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnemonic.
        /// </summary>
        internal static string SourceName {
            get {
                return ResourceManager.GetString("SourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Src.
        /// </summary>
        internal static string SourcePluginAppender {
            get {
                return ResourceManager.GetString("SourcePluginAppender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool Start {
            get {
                object obj = ResourceManager.GetObject("Start", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemExplorer.
        /// </summary>
        internal static string SystemExplorer {
            get {
                return ResourceManager.GetString("SystemExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnemonic Editor.
        /// </summary>
        internal static string TabText {
            get {
                return ResourceManager.GetString("TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnemonic Editor *.
        /// </summary>
        internal static string TabTextUnsaved {
            get {
                return ResourceManager.GetString("TabTextUnsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool TVKill {
            get {
                object obj = ResourceManager.GetObject("TVKill", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.TestSLATE.Mnemonic.llb.
        /// </summary>
        internal static string VILLBName {
            get {
                return ResourceManager.GetString("VILLBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnemonic.vi.
        /// </summary>
        internal static string VIName {
            get {
                return ResourceManager.GetString("VIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared\SYSCOM.
        /// </summary>
        internal static string VIRelativeSourceDir {
            get {
                return ResourceManager.GetString("VIRelativeSourceDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool WritesToRFM {
            get {
                object obj = ResourceManager.GetObject("WritesToRFM", resourceCulture);
                return ((bool)(obj));
            }
        }
    }
}
